---
- hosts: localhost
  gather_facts: true
  become: true
  roles:
    - role: andrewrothstein.minikube
    - role: mongrelion.docker
      default_docker_config:
        storage-driver: aufs
        log-level: info
    - role: andrewrothstein.kubernetes-helm
      kubernetes_helm_ver: v2.7.2
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
      with_items:
        - socat
